language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python marketplace/manage.py makemigrations
  - python marketplace/manage.py migrate
# command to run tests
script:
  - yes | python marketplace/manage.py test courses auth0login
