# Generated by Django 2.2.5 on 2019-10-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth0login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='picture',
        ),
    ]
