# Generated by Django 2.2.5 on 2019-10-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth0login', '0002_auto_20191012_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='image',
        ),
    ]
