# Generated by Django 2.2.5 on 2019-10-13 12:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=6),
        ),
    ]
