# Generated by Django 2.2.5 on 2019-10-13 12:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=9),
        ),
    ]
