# Generated by Django 2.2.5 on 2019-10-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191013_1210'),
        ('courses', '0002_courseentry_lesson'),
    ]

    operations = [
    ]
