# Generated by Django 2.2.5 on 2019-11-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191019_1306'),
        ('courses', '0005_auto_20191019_1220'),
    ]

    operations = [
    ]
