# Generated by Django 2.2.5 on 2020-04-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200406_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='student',
            new_name='user',
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_course_owner',
            field=models.BooleanField(default=False),
        ),
    ]
