# Generated by Django 2.2.5 on 2020-04-06 17:20

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200406_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, upload_to='assignments/', validators=[courses.validators.validate_file_extension]),
        ),
    ]
