# Generated by Django 2.2.5 on 2020-04-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200406_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=200)),
                ('chatId', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
